from __future__ import annotations

from typing import Protocol

from agent_core.memory.memory_records import MemoryQuery, MemoryRecord


class MemoryStoreProtocol(Protocol):
    def write(self, record: MemoryRecord) -> None: ...
    def search(self, query: MemoryQuery) -> list[MemoryRecord]: ...
    def get(self, memory_id: str) -> MemoryRecord | None: ...
    def write_note(self, name: str, content: str) -> None: ...
    def read_note(self, name: str) -> str | None: ...
    def list_notes(self) -> list[str]: ...


class MemoryAgentProtocol(Protocol):
    def write_note(self, name: str, content: str) -> MemoryRecord: ...
    def read_note(self, name: str) -> str | None: ...
    def list_notes(self) -> list[str]: ...
    def save_fact(self, content: str, tags: list[str] | None = None) -> MemoryRecord: ...
    def save_preference(self, content: str, tags: list[str] | None = None) -> MemoryRecord: ...
    def save_decision(self, content: str, tags: list[str] | None = None) -> MemoryRecord: ...
    def search_memory(self, query: str, limit: int = 10) -> list[MemoryRecord]: ...
    def summarize_memory(self, query: str = "", limit: int = 10) -> str: ...
